export const data = [
  {
    recordID: '1',
    displayName: 'Jane Smith',
    phoneNumbers: [{label: 'home', number: '987-654-3210'}],
    emailAddresses: [{label: 'personal', email: 'jane.smith@example.com'}],
  },
  {
    recordID: '2',
    displayName: 'John Doe',
    phoneNumbers: [{label: 'mobile', number: '123-456-7890'}],
    emailAddresses: [{label: 'work', email: 'john.doe@example.com'}],
  },
  {
    recordID: '3',
    displayName: 'Alice Johnson',
    phoneNumbers: [{label: 'home', number: '555-123-4567'}],
    emailAddresses: [{label: 'personal', email: 'alice.johnson@example.com'}],
  },
  {
    recordID: '4',
    displayName: 'Bob Williams',
    phoneNumbers: [{label: 'work', number: '444-987-6543'}],
    emailAddresses: [{label: 'personal', email: 'bob.williams@example.com'}],
  },
  {
    recordID: '5',
    displayName: 'Emma Brown',
    phoneNumbers: [{label: 'mobile', number: '666-555-4321'}],
    emailAddresses: [{label: 'work', email: 'emma.brown@example.com'}],
  },
  {
    recordID: '6',
    displayName: 'Michael Davis',
    phoneNumbers: [{label: 'home', number: '777-333-2222'}],
    emailAddresses: [{label: 'personal', email: 'michael.davis@example.com'}],
  },
  {
    recordID: '7',
    displayName: 'Sarah Wilson',
    phoneNumbers: [{label: 'mobile', number: '888-777-6666'}],
    emailAddresses: [{label: 'work', email: 'sarah.wilson@example.com'}],
  },
  {
    recordID: '8',
    displayName: 'David Martinez',
    phoneNumbers: [{label: 'home', number: '999-888-7777'}],
    emailAddresses: [{label: 'personal', email: 'david.martinez@example.com'}],
  },
  {
    recordID: '9',
    displayName: 'Emily Anderson',
    phoneNumbers: [{label: 'work', number: '111-222-3333'}],
    emailAddresses: [{label: 'personal', email: 'emily.anderson@example.com'}],
  },
  {
    recordID: '10',
    displayName: 'Matthew Taylor',
    phoneNumbers: [{label: 'mobile', number: '222-333-4444'}],
    emailAddresses: [{label: 'work', email: 'matthew.taylor@example.com'}],
  },
  {
    recordID: '11',
    displayName: 'Olivia Moore',
    phoneNumbers: [{label: 'home', number: '123-456-7890'}],
    emailAddresses: [{label: 'personal', email: 'olivia.moore@example.com'}],
  },
  {
    recordID: '12',
    displayName: 'Daniel Jackson',
    phoneNumbers: [{label: 'mobile', number: '234-567-8901'}],
    emailAddresses: [{label: 'work', email: 'daniel.jackson@example.com'}],
  },
  {
    recordID: '13',
    displayName: 'Ava Garcia',
    phoneNumbers: [{label: 'home', number: '345-678-9012'}],
    emailAddresses: [{label: 'personal', email: 'ava.garcia@example.com'}],
  },
  {
    recordID: '14',
    displayName: 'James Brown',
    phoneNumbers: [{label: 'work', number: '456-789-0123'}],
    emailAddresses: [{label: 'personal', email: 'james.brown@example.com'}],
  },
  {
    recordID: '15',
    displayName: 'Mia Rodriguez',
    phoneNumbers: [{label: 'mobile', number: '567-890-1234'}],
    emailAddresses: [{label: 'work', email: 'mia.rodriguez@example.com'}],
  },
  {
    recordID: '16',
    displayName: 'William Lee',
    phoneNumbers: [{label: 'home', number: '678-901-2345'}],
    emailAddresses: [{label: 'personal', email: 'william.lee@example.com'}],
  },
  {
    recordID: '17',
    displayName: 'Sophia Hernandez',
    phoneNumbers: [{label: 'mobile', number: '789-012-3456'}],
    emailAddresses: [{label: 'work', email: 'sophia.hernandez@example.com'}],
  },
  {
    recordID: '18',
    displayName: 'Ethan Gonzalez',
    phoneNumbers: [{label: 'home', number: '890-123-4567'}],
    emailAddresses: [{label: 'personal', email: 'ethan.gonzalez@example.com'}],
  },
  {
    recordID: '19',
    displayName: 'Isabella Wilson',
    phoneNumbers: [{label: 'work', number: '901-234-5678'}],
    emailAddresses: [{label: 'personal', email: 'isabella.wilson@example.com'}],
  },
  {
    recordID: '20',
    displayName: 'Alexander Taylor',
    phoneNumbers: [{label: 'mobile', number: '012-345-6789'}],
    emailAddresses: [{label: 'work', email: 'alexander.taylor@example.com'}],
  },
  {
    recordID: '21',
    displayName: 'Charlotte Martinez',
    phoneNumbers: [{label: 'home', number: '345-678-9012'}],
    emailAddresses: [
      {label: 'personal', email: 'charlotte.martinez@example.com'},
    ],
  },
  {
    recordID: '22',
    displayName: 'Benjamin Anderson',
    phoneNumbers: [{label: 'mobile', number: '456-789-0123'}],
    emailAddresses: [{label: 'work', email: 'benjamin.anderson@example.com'}],
  },
  {
    recordID: '23',
    displayName: 'Amelia Thomas',
    phoneNumbers: [{label: 'home', number: '567-890-1234'}],
    emailAddresses: [{label: 'personal', email: 'amelia.thomas@example.com'}],
  },
  {
    recordID: '24',
    displayName: 'Daniel Jackson',
    phoneNumbers: [{label: 'work', number: '678-901-2345'}],
    emailAddresses: [{label: 'personal', email: 'daniel.jackson@example.com'}],
  },
  {
    recordID: '25',
    displayName: 'Evelyn White',
    phoneNumbers: [{label: 'mobile', number: '789-012-3456'}],
    emailAddresses: [{label: 'work', email: 'evelyn.white@example.com'}],
  },
  {
    recordID: '26',
    displayName: 'Michael Harris',
    phoneNumbers: [{label: 'home', number: '890-123-4567'}],
    emailAddresses: [{label: 'personal', email: 'michael.harris@example.com'}],
  },
  {
    recordID: '27',
    displayName: 'Olivia Clark',
    phoneNumbers: [{label: 'mobile', number: '901-234-5678'}],
    emailAddresses: [{label: 'work', email: 'olivia.clark@example.com'}],
  },
  {
    recordID: '28',
    displayName: 'William King',
    phoneNumbers: [{label: 'home', number: '012-345-6789'}],
    emailAddresses: [{label: 'personal', email: 'william.king@example.com'}],
  },
  {
    recordID: '29',
    displayName: 'Sophia Lewis',
    phoneNumbers: [{label: 'work', number: '123-456-7890'}],
    emailAddresses: [{label: 'personal', email: 'sophia.lewis@example.com'}],
  },
  {
    recordID: '30',
    displayName: 'James Hill',
    phoneNumbers: [{label: 'mobile', number: '234-567-8901'}],
    emailAddresses: [{label: 'work', email: 'james.hill@example.com'}],
  },
  {
    recordID: '31',
    displayName: 'Olivia Green',
    phoneNumbers: [{label: 'home', number: '345-678-9012'}],
    emailAddresses: [{label: 'personal', email: 'olivia.green@example.com'}],
  },
  {
    recordID: '32',
    displayName: 'Daniel Carter',
    phoneNumbers: [{label: 'mobile', number: '456-789-0123'}],
    emailAddresses: [{label: 'work', email: 'daniel.carter@example.com'}],
  },
  {
    recordID: '33',
    displayName: 'Ava Adams',
    phoneNumbers: [{label: 'home', number: '567-890-1234'}],
    emailAddresses: [{label: 'personal', email: 'ava.adams@example.com'}],
  },
  {
    recordID: '34',
    displayName: 'James Nelson',
    phoneNumbers: [{label: 'work', number: '678-901-2345'}],
    emailAddresses: [{label: 'personal', email: 'james.nelson@example.com'}],
  },
  {
    recordID: '35',
    displayName: 'Mia Walker',
    phoneNumbers: [{label: 'mobile', number: '789-012-3456'}],
    emailAddresses: [{label: 'work', email: 'mia.walker@example.com'}],
  },
  {
    recordID: '36',
    displayName: 'William Young',
    phoneNumbers: [{label: 'home', number: '890-123-4567'}],
    emailAddresses: [{label: 'personal', email: 'william.young@example.com'}],
  },
  {
    recordID: '37',
    displayName: 'Sophia Scott',
    phoneNumbers: [{label: 'mobile', number: '901-234-5678'}],
    emailAddresses: [{label: 'work', email: 'sophia.scott@example.com'}],
  },
  {
    recordID: '38',
    displayName: 'Ethan Wright',
    phoneNumbers: [{label: 'home', number: '012-345-6789'}],
    emailAddresses: [{label: 'personal', email: 'ethan.wright@example.com'}],
  },
  {
    recordID: '39',
    displayName: 'Isabella Brown',
    phoneNumbers: [{label: 'work', number: '123-456-7890'}],
    emailAddresses: [{label: 'personal', email: 'isabella.brown@example.com'}],
  },
  {
    recordID: '40',
    displayName: 'Alexander Evans',
    phoneNumbers: [{label: 'mobile', number: '234-567-8901'}],
    emailAddresses: [{label: 'work', email: 'alexander.evans@example.com'}],
  },
  {
    recordID: '41',
    displayName: 'Charlotte Wilson',
    phoneNumbers: [{label: 'home', number: '345-678-9012'}],
    emailAddresses: [
      {label: 'personal', email: 'charlotte.wilson@example.com'},
    ],
  },
  {
    recordID: '42',
    displayName: 'Benjamin Martinez',
    phoneNumbers: [{label: 'mobile', number: '456-789-0123'}],
    emailAddresses: [{label: 'work', email: 'benjamin.martinez@example.com'}],
  },
  {
    recordID: '43',
    displayName: 'Amelia Hill',
    phoneNumbers: [{label: 'home', number: '567-890-1234'}],
    emailAddresses: [{label: 'personal', email: 'amelia.hill@example.com'}],
  },
  {
    recordID: '44',
    displayName: 'Daniel Lewis',
    phoneNumbers: [{label: 'work', number: '678-901-2345'}],
    emailAddresses: [{label: 'personal', email: 'daniel.lewis@example.com'}],
  },
  {
    recordID: '45',
    displayName: 'Evelyn Adams',
    phoneNumbers: [{label: 'mobile', number: '789-012-3456'}],
    emailAddresses: [{label: 'work', email: 'evelyn.adams@example.com'}],
  },
  {
    recordID: '46',
    displayName: 'Michael Hernandez',
    phoneNumbers: [{label: 'home', number: '890-123-4567'}],
    emailAddresses: [
      {label: 'personal', email: 'michael.hernandez@example.com'},
    ],
  },
  {
    recordID: '47',
    displayName: 'Olivia Davis',
    phoneNumbers: [{label: 'mobile', number: '901-234-5678'}],
    emailAddresses: [{label: 'work', email: 'olivia.davis@example.com'}],
  },
  {
    recordID: '48',
    displayName: 'William Martinez',
    phoneNumbers: [{label: 'home', number: '012-345-6789'}],
    emailAddresses: [
      {label: 'personal', email: 'william.martinez@example.com'},
    ],
  },
  {
    recordID: '49',
    displayName: 'Sophia Jackson',
    phoneNumbers: [{label: 'work', number: '123-456-7890'}],
    emailAddresses: [{label: 'personal', email: 'sophia.jackson@example.com'}],
  },
  {
    recordID: '50',
    displayName: 'James Anderson',
    phoneNumbers: [{label: 'mobile', number: '234-567-8901'}],
    emailAddresses: [{label: 'work', email: 'james.anderson@example.com'}],
  },
  {
    recordID: '51',
    displayName: 'Emma Martinez',
    phoneNumbers: [{label: 'home', number: '345-678-9012'}],
    emailAddresses: [{label: 'personal', email: 'emma.martinez@example.com'}],
  },
  {
    recordID: '52',
    displayName: 'Michael Thompson',
    phoneNumbers: [{label: 'mobile', number: '456-789-0123'}],
    emailAddresses: [{label: 'work', email: 'michael.thompson@example.com'}],
  },
  {
    recordID: '53',
    displayName: 'Olivia Allen',
    phoneNumbers: [{label: 'home', number: '567-890-1234'}],
    emailAddresses: [{label: 'personal', email: 'olivia.allen@example.com'}],
  },
  {
    recordID: '54',
    displayName: 'William Perez',
    phoneNumbers: [{label: 'work', number: '678-901-2345'}],
    emailAddresses: [{label: 'personal', email: 'william.perez@example.com'}],
  },
  {
    recordID: '55',
    displayName: 'Sophia Garcia',
    phoneNumbers: [{label: 'mobile', number: '789-012-3456'}],
    emailAddresses: [{label: 'work', email: 'sophia.garcia@example.com'}],
  },
  {
    recordID: '56',
    displayName: 'James Rodriguez',
    phoneNumbers: [{label: 'home', number: '890-123-4567'}],
    emailAddresses: [{label: 'personal', email: 'james.rodriguez@example.com'}],
  },
  {
    recordID: '57',
    displayName: 'Mia Martinez',
    phoneNumbers: [{label: 'mobile', number: '901-234-5678'}],
    emailAddresses: [{label: 'work', email: 'mia.martinez@example.com'}],
  },
  {
    recordID: '58',
    displayName: 'Ethan Lopez',
    phoneNumbers: [{label: 'home', number: '012-345-6789'}],
    emailAddresses: [{label: 'personal', email: 'ethan.lopez@example.com'}],
  },
  {
    recordID: '59',
    displayName: 'Isabella Hernandez',
    phoneNumbers: [{label: 'work', number: '123-456-7890'}],
    emailAddresses: [
      {label: 'personal', email: 'isabella.hernandez@example.com'},
    ],
  },
  {
    recordID: '60',
    displayName: 'Alexander Adams',
    phoneNumbers: [{label: 'mobile', number: '234-567-8901'}],
    emailAddresses: [{label: 'work', email: 'alexander.adams@example.com'}],
  },
  {
    recordID: '61',
    displayName: 'Charlotte Thomas',
    phoneNumbers: [{label: 'home', number: '345-678-9012'}],
    emailAddresses: [
      {label: 'personal', email: 'charlotte.thomas@example.com'},
    ],
  },
  {
    recordID: '62',
    displayName: 'Benjamin Nelson',
    phoneNumbers: [{label: 'mobile', number: '456-789-0123'}],
    emailAddresses: [{label: 'work', email: 'benjamin.nelson@example.com'}],
  },
  {
    recordID: '63',
    displayName: 'Amelia Walker',
    phoneNumbers: [{label: 'home', number: '567-890-1234'}],
    emailAddresses: [{label: 'personal', email: 'amelia.walker@example.com'}],
  },
  {
    recordID: '64',
    displayName: 'Daniel Scott',
    phoneNumbers: [{label: 'work', number: '678-901-2345'}],
    emailAddresses: [{label: 'personal', email: 'daniel.scott@example.com'}],
  },
  {
    recordID: '65',
    displayName: 'Evelyn Young',
    phoneNumbers: [{label: 'mobile', number: '789-012-3456'}],
    emailAddresses: [{label: 'work', email: 'evelyn.young@example.com'}],
  },
  {
    recordID: '66',
    displayName: 'Michael Wright',
    phoneNumbers: [{label: 'home', number: '890-123-4567'}],
    emailAddresses: [{label: 'personal', email: 'michael.wright@example.com'}],
  },
  {
    recordID: '67',
    displayName: 'Olivia King',
    phoneNumbers: [{label: 'mobile', number: '901-234-5678'}],
    emailAddresses: [{label: 'work', email: 'olivia.king@example.com'}],
  },
  {
    recordID: '68',
    displayName: 'William Lewis',
    phoneNumbers: [{label: 'home', number: '012-345-6789'}],
    emailAddresses: [{label: 'personal', email: 'william.lewis@example.com'}],
  },
  {
    recordID: '69',
    displayName: 'Sophia Hernandez',
    phoneNumbers: [{label: 'work', number: '123-456-7890'}],
    emailAddresses: [
      {label: 'personal', email: 'sophia.hernandez2@example.com'},
    ],
  },
  {
    recordID: '70',
    displayName: 'James White',
    phoneNumbers: [{label: 'mobile', number: '234-567-8901'}],
    emailAddresses: [{label: 'work', email: 'james.white@example.com'}],
  },
  {
    recordID: '71',
    displayName: 'Mia Perez',
    phoneNumbers: [{label: 'home', number: '345-678-9012'}],
    emailAddresses: [{label: 'personal', email: 'mia.perez@example.com'}],
  },
  {
    recordID: '72',
    displayName: 'Ethan Gonzalez',
    phoneNumbers: [{label: 'mobile', number: '456-789-0123'}],
    emailAddresses: [{label: 'work', email: 'ethan.gonzalez2@example.com'}],
  },
  {
    recordID: '73',
    displayName: 'Isabella Johnson',
    phoneNumbers: [{label: 'home', number: '567-890-1234'}],
    emailAddresses: [
      {label: 'personal', email: 'isabella.johnson2@example.com'},
    ],
  },
  {
    recordID: '74',
    displayName: 'Alexander Taylor',
    phoneNumbers: [{label: 'work', number: '678-901-2345'}],
    emailAddresses: [
      {label: 'personal', email: 'alexander.taylor2@example.com'},
    ],
  },
  {
    recordID: '75',
    displayName: 'Charlotte Martinez',
    phoneNumbers: [{label: 'mobile', number: '789-012-3456'}],
    emailAddresses: [{label: 'work', email: 'charlotte.martinez2@example.com'}],
  },
  {
    recordID: '76',
    displayName: 'Benjamin Brown',
    phoneNumbers: [{label: 'home', number: '890-123-4567'}],
    emailAddresses: [{label: 'personal', email: 'benjamin.brown2@example.com'}],
  },
  {
    recordID: '77',
    displayName: 'Amelia Davis',
    phoneNumbers: [{label: 'mobile', number: '901-234-5678'}],
    emailAddresses: [{label: 'work', email: 'amelia.davis2@example.com'}],
  },
  {
    recordID: '78',
    displayName: 'Daniel Wilson',
    phoneNumbers: [{label: 'home', number: '012-345-6789'}],
    emailAddresses: [{label: 'personal', email: 'daniel.wilson2@example.com'}],
  },
  {
    recordID: '79',
    displayName: 'Evelyn Anderson',
    phoneNumbers: [{label: 'work', number: '123-456-7890'}],
    emailAddresses: [
      {label: 'personal', email: 'evelyn.anderson2@example.com'},
    ],
  },
  {
    recordID: '80',
    displayName: 'Michael Thomas',
    phoneNumbers: [{label: 'mobile', number: '234-567-8901'}],
    emailAddresses: [{label: 'work', email: 'michael.thomas2@example.com'}],
  },
  {
    recordID: '81',
    displayName: 'Olivia Garcia',
    phoneNumbers: [{label: 'home', number: '345-678-9012'}],
    emailAddresses: [{label: 'personal', email: 'olivia.garcia2@example.com'}],
  },
  {
    recordID: '82',
    displayName: 'William Rodriguez',
    phoneNumbers: [{label: 'mobile', number: '456-789-0123'}],
    emailAddresses: [{label: 'work', email: 'william.rodriguez2@example.com'}],
  },
  {
    recordID: '83',
    displayName: 'Sophia Martinez',
    phoneNumbers: [{label: 'home', number: '567-890-1234'}],
    emailAddresses: [
      {label: 'personal', email: 'sophia.martinez2@example.com'},
    ],
  },
  {
    recordID: '84',
    displayName: 'James Thompson',
    phoneNumbers: [{label: 'work', number: '678-901-2345'}],
    emailAddresses: [{label: 'personal', email: 'james.thompson2@example.com'}],
  },
  {
    recordID: '85',
    displayName: 'Mia Allen',
    phoneNumbers: [{label: 'mobile', number: '789-012-3456'}],
    emailAddresses: [{label: 'work', email: 'mia.allen2@example.com'}],
  },
  {
    recordID: '86',
    displayName: 'Ethan Perez',
    phoneNumbers: [{label: 'home', number: '890-123-4567'}],
    emailAddresses: [{label: 'personal', email: 'ethan.perez2@example.com'}],
  },
  {
    recordID: '87',
    displayName: 'Isabella Gonzalez',
    phoneNumbers: [{label: 'mobile', number: '901-234-5678'}],
    emailAddresses: [{label: 'work', email: 'isabella.gonzalez2@example.com'}],
  },
  {
    recordID: '88',
    displayName: 'Alexander Johnson',
    phoneNumbers: [{label: 'home', number: '012-345-6789'}],
    emailAddresses: [
      {label: 'personal', email: 'alexander.johnson2@example.com'},
    ],
  },
  {
    recordID: '89',
    displayName: 'Charlotte Taylor',
    phoneNumbers: [{label: 'work', number: '123-456-7890'}],
    emailAddresses: [
      {label: 'personal', email: 'charlotte.taylor2@example.com'},
    ],
  },
  {
    recordID: '90',
    displayName: 'Benjamin Scott',
    phoneNumbers: [{label: 'mobile', number: '234-567-8901'}],
    emailAddresses: [{label: 'work', email: 'benjamin.scott2@example.com'}],
  },
  {
    recordID: '91',
    displayName: 'Amelia White',
    phoneNumbers: [{label: 'home', number: '345-678-9012'}],
    emailAddresses: [{label: 'personal', email: 'amelia.white2@example.com'}],
  },
  {
    recordID: '92',
    displayName: 'Daniel Perez',
    phoneNumbers: [{label: 'work', number: '456-789-0123'}],
    emailAddresses: [{label: 'personal', email: 'daniel.perez2@example.com'}],
  },
  {
    recordID: '93',
    displayName: 'Evelyn Gonzalez',
    phoneNumbers: [{label: 'home', number: '567-890-1234'}],
    emailAddresses: [
      {label: 'personal', email: 'evelyn.gonzalez2@example.com'},
    ],
  },
  {
    recordID: '94',
    displayName: 'Michael Johnson',
    phoneNumbers: [{label: 'mobile', number: '678-901-2345'}],
    emailAddresses: [{label: 'work', email: 'michael.johnson2@example.com'}],
  },
  {
    recordID: '95',
    displayName: 'Olivia Taylor',
    phoneNumbers: [{label: 'home', number: '789-012-3456'}],
    emailAddresses: [{label: 'personal', email: 'olivia.taylor2@example.com'}],
  },
  {
    recordID: '96',
    displayName: 'William Scott',
    phoneNumbers: [{label: 'mobile', number: '890-123-4567'}],
    emailAddresses: [{label: 'work', email: 'william.scott2@example.com'}],
  },
  {
    recordID: '97',
    displayName: 'Sophia White',
    phoneNumbers: [{label: 'home', number: '901-234-5678'}],
    emailAddresses: [{label: 'personal', email: 'sophia.white2@example.com'}],
  },
  {
    recordID: '98',
    displayName: 'James Perez',
    phoneNumbers: [{label: 'work', number: '012-345-6789'}],
    emailAddresses: [{label: 'personal', email: 'james.perez2@example.com'}],
  },
  {
    recordID: '99',
    displayName: 'Mia Gonzalez',
    phoneNumbers: [{label: 'mobile', number: '123-456-7890'}],
    emailAddresses: [{label: 'work', email: 'mia.gonzalez2@example.com'}],
  },
  {
    recordID: '100',
    displayName: 'Ethan Johnson',
    phoneNumbers: [{label: 'home', number: '234-567-8901'}],
    emailAddresses: [{label: 'personal', email: 'ethan.johnson2@example.com'}],
  },
];
